### ISSUE TITLE
[Feature] 主題配色與字體字型調整

### ISSUE THREAD

**Issue by Bosh-Kuo** [Bosh-Kuo/Bosh-Docusaurus-Dev-Notes#7]
## Describe the feature request

目前的字型、字體、主題配色、字體大小與行距都尚未客製化，閱讀體驗不是很好

## TODO

- [x] 修改主題配色(亮色/暗色模式)
- [x] 修改字型、字體
- [x] 調整 markdown h2, h3 樣式
- [x] 調整 code 樣式
- [x] 字體大小、行距
